export const trendPlatforms = ["TikTok", "Instagram", "Facebook", "X", "Reddit", "Google Trends", "YouTube"];

export const trendCategories = [
  "Trending Topics",
  "Trending Hashtags",
  "Trending Sounds",
  "Trending Videos",
  "Trending Searches",
  "Industry Trends",
  "Local Trends",
  "Competitor Trends",
];

export const trendFilterOptions = {
  countries: ["United States", "Canada", "United Kingdom", "Australia"],
  states: ["California", "New York", "Texas", "Florida", "Ontario"],
  cities: ["Los Angeles", "New York City", "Austin", "Miami", "Toronto"],
  industries: ["Fitness", "SaaS", "Beauty", "Food & Beverage", "Real Estate", "Local Services"],
  timeRanges: ["Past 24 hours", "Past 7 days", "Past 30 days", "Past 90 days"],
};

const opportunityTemplates = {
  "Trending Topics": {
    postIdeas: ["Break down why this trend matters now", "Share a founder POV on the conversation"],
    videoIdeas: ["Three fast examples with on-screen captions", "Street-style customer reaction clip"],
    hooks: ["Everyone is missing the real reason this is taking off.", "If your audience cares about this, post today."],
    captions: ["The window is open now. Here is the angle worth testing.", "Save this before the trend gets crowded."],
    adCopy: ["Turn today's conversation into qualified demand with a sharper offer.", "Meet buyers while attention is already moving."],
    emailIdeas: ["Trend briefing with one practical action", "Curated takeaways for busy subscribers"],
    campaignIdeas: ["48-hour social sprint", "Trend-to-offer retargeting sequence"],
  },
  "Trending Hashtags": {
    postIdeas: ["Publish a carousel explaining the hashtag context", "Pair the hashtag with a customer proof point"],
    videoIdeas: ["Hashtag challenge remix", "Before and after mini story"],
    hooks: ["This hashtag is moving faster than the feed can explain.", "Use this tag only if your angle is specific."],
    captions: ["Context wins. Here is the version your audience will actually care about.", "A trend is not a strategy until it has a point of view."],
    adCopy: ["Join high-intent discovery with creative that feels native.", "Ride the hashtag without sounding like everyone else."],
    emailIdeas: ["Hashtag watchlist and examples", "Audience angle swipe file"],
    campaignIdeas: ["Creator duet challenge", "Hashtag landing page test"],
  },
  "Trending Sounds": {
    postIdeas: ["Explain the emotion behind the sound", "Show a product moment that matches the beat"],
    videoIdeas: ["Seven-second transformation clip", "Team reaction using the audio cue"],
    hooks: ["This sound is becoming a shortcut for attention.", "The audio is popular, but the story still has to carry it."],
    captions: ["Sound on for the moment your audience already recognizes.", "Use familiar audio to make the message land faster."],
    adCopy: ["Native-feeling video creative built around an emerging sound.", "Make product education feel like the feed."],
    emailIdeas: ["Sound trend recap for creators", "Creative prompt pack"],
    campaignIdeas: ["UGC sound brief", "Reels and Shorts audio test"],
  },
  "Trending Videos": {
    postIdeas: ["Screenshot the format and explain why it works", "Turn the video structure into a brand story"],
    videoIdeas: ["Format remix with customer objection", "Point-of-view explainer using the same pacing"],
    hooks: ["The format is the opportunity, not the exact video.", "Here is the reusable structure behind the breakout clip."],
    captions: ["Borrow the structure. Make the insight yours.", "This format is built for fast comprehension."],
    adCopy: ["Adapt proven short-form structure into conversion creative.", "Use the format your buyers are already watching."],
    emailIdeas: ["Video teardown with reusable beats", "Creative briefing email"],
    campaignIdeas: ["Short-form format lab", "Video retargeting ladder"],
  },
  "Trending Searches": {
    postIdeas: ["Answer the search in plain language", "Compare options for buyers at the research stage"],
    videoIdeas: ["Search result explainer", "Myth versus fact response"],
    hooks: ["Search demand is rising before the market has good answers.", "People are asking this right now. Be the useful result."],
    captions: ["A simple answer can become the highest-converting asset.", "Search intent is a content brief hiding in public."],
    adCopy: ["Capture rising intent before competitors bid it up.", "Answer the question and earn the click."],
    emailIdeas: ["FAQ sequence built from rising searches", "Search trend digest"],
    campaignIdeas: ["SEO content sprint", "Paid search validation test"],
  },
  "Industry Trends": {
    postIdeas: ["Translate the macro trend into a customer action", "Publish a mini benchmark"],
    videoIdeas: ["Industry pulse update", "Expert commentary clip"],
    hooks: ["This industry shift is closer to your buyer than it looks.", "The brands that move early will sound more useful."],
    captions: ["Macro trend, practical move.", "Your next campaign angle may already be visible in the data."],
    adCopy: ["Position your offer against where the market is heading.", "Turn industry momentum into a timely buying reason."],
    emailIdeas: ["Executive trend memo", "Industry benchmark newsletter"],
    campaignIdeas: ["Thought leadership funnel", "Category POV campaign"],
  },
  "Local Trends": {
    postIdeas: ["Local guide tied to the moment", "Neighborhood-specific customer story"],
    videoIdeas: ["On-location trend response", "Local creator collaboration"],
    hooks: ["This is not just trending online. It is showing up locally.", "Your city is giving you a timely campaign angle."],
    captions: ["Built for the people seeing this in their own neighborhood.", "Local relevance turns a trend into action."],
    adCopy: ["Reach nearby buyers with a trend they already recognize.", "Make the local moment bookable, visitable, or shareable."],
    emailIdeas: ["Local weekend trend email", "City-specific offer note"],
    campaignIdeas: ["Geo-targeted flash campaign", "Local partnership activation"],
  },
  "Competitor Trends": {
    postIdeas: ["Position against the competitor angle with proof", "Share a transparent comparison"],
    videoIdeas: ["Competitor claim teardown", "Alternative approach explainer"],
    hooks: ["Your competitors are training the market. Use that demand better.", "Do not copy the angle. Answer the gap it leaves."],
    captions: ["Competitive noise is a signal when you know what to listen for.", "The opening is in what they are not saying."],
    adCopy: ["Convert competitor curiosity with a sharper reason to switch.", "Capture demand created by the category conversation."],
    emailIdeas: ["Switching guide", "Competitor comparison nurture"],
    campaignIdeas: ["Conquesting ad set", "Comparison landing page campaign"],
  },
};

export const mockTrends = [
  {
    id: "trend-local-recovery",
    category: "Trending Topics",
    title: "Recovery routines for busy professionals",
    signal: "Wellness creators are reframing recovery as productivity insurance.",
    platform: "TikTok",
    country: "United States",
    state: "California",
    city: "Los Angeles",
    industry: "Fitness",
    score: 94,
    growth: 41,
    lifespan: "9-12 days",
    difficulty: "Medium",
    audience: "Time-starved professionals, 28-44",
    suggestedPlatforms: ["TikTok", "Instagram", "YouTube"],
  },
  {
    id: "trend-ai-workflows",
    category: "Trending Searches",
    title: "AI workflow templates",
    signal: "Searches are moving from generic AI tools to repeatable business workflows.",
    platform: "Google Trends",
    country: "United States",
    state: "New York",
    city: "New York City",
    industry: "SaaS",
    score: 91,
    growth: 36,
    lifespan: "3-5 weeks",
    difficulty: "Low",
    audience: "Small business operators and marketing leads",
    suggestedPlatforms: ["Google Trends", "YouTube", "Reddit"],
  },
  {
    id: "trend-sound-reset",
    category: "Trending Sounds",
    title: "Soft reset morning audio",
    signal: "A calm audio cue is spreading across wellness, beauty, and home routines.",
    platform: "Instagram",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    industry: "Beauty",
    score: 88,
    growth: 52,
    lifespan: "6-10 days",
    difficulty: "Low",
    audience: "Routine builders and self-care shoppers",
    suggestedPlatforms: ["Instagram", "TikTok", "Facebook"],
  },
  {
    id: "trend-video-transparent-price",
    category: "Trending Videos",
    title: "Transparent pricing breakdowns",
    signal: "Short videos showing exactly where customer money goes are outperforming polished promos.",
    platform: "YouTube",
    country: "United States",
    state: "Texas",
    city: "Austin",
    industry: "Local Services",
    score: 86,
    growth: 29,
    lifespan: "2-4 weeks",
    difficulty: "Medium",
    audience: "Value-conscious local buyers",
    suggestedPlatforms: ["YouTube", "TikTok", "Facebook"],
  },
  {
    id: "trend-hashtag-third-place",
    category: "Trending Hashtags",
    title: "#ThirdPlaceEnergy",
    signal: "Food, fitness, and retail brands are using community-space language to drive visits.",
    platform: "X",
    country: "United States",
    state: "Florida",
    city: "Miami",
    industry: "Food & Beverage",
    score: 82,
    growth: 47,
    lifespan: "5-8 days",
    difficulty: "Medium",
    audience: "Local community seekers and repeat visitors",
    suggestedPlatforms: ["Instagram", "X", "TikTok"],
  },
  {
    id: "trend-industry-micro-gyms",
    category: "Industry Trends",
    title: "Micro-gym retention programs",
    signal: "Boutique fitness operators are packaging accountability as a subscription benefit.",
    platform: "Reddit",
    country: "United States",
    state: "California",
    city: "Los Angeles",
    industry: "Fitness",
    score: 79,
    growth: 24,
    lifespan: "6-8 weeks",
    difficulty: "High",
    audience: "Gym owners and high-intent local members",
    suggestedPlatforms: ["Reddit", "Facebook", "Instagram"],
  },
  {
    id: "trend-local-summer-popups",
    category: "Local Trends",
    title: "After-work summer popups",
    signal: "City audiences are sharing lightweight weekday events that feel easier than weekend plans.",
    platform: "Facebook",
    country: "United States",
    state: "New York",
    city: "New York City",
    industry: "Food & Beverage",
    score: 77,
    growth: 33,
    lifespan: "2-3 weeks",
    difficulty: "Low",
    audience: "Urban professionals looking for low-friction plans",
    suggestedPlatforms: ["Facebook", "Instagram", "TikTok"],
  },
  {
    id: "trend-competitor-checklists",
    category: "Competitor Trends",
    title: "Competitor checklist lead magnets",
    signal: "Competing SaaS brands are trading checklist downloads for mid-funnel intent.",
    platform: "Reddit",
    country: "United Kingdom",
    state: "New York",
    city: "New York City",
    industry: "SaaS",
    score: 74,
    growth: 18,
    lifespan: "4-6 weeks",
    difficulty: "High",
    audience: "Evaluation-stage operators comparing solutions",
    suggestedPlatforms: ["Reddit", "Google Trends", "X"],
  },
];

export function enrichTrend(trend) {
  const templates = opportunityTemplates[trend.category] || opportunityTemplates["Trending Topics"];
  return {
    ...trend,
    ai: templates,
  };
}
